# -*- coding: utf-8 -*-
"""AUDIO.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6Cu-WNyM1ahkov3cqVOIUQF_4H29y3M
"""

# Complete Audiobook Guide Generator using IBM Granite 3.3 2B Instruct
# Run this entire cell in Google Colab

# Install required packages
!pip install -q transformers accelerate gradio torch

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import warnings
warnings.filterwarnings('ignore')

# Initialize model and tokenizer
print("Loading IBM Granite 3.3 2B Instruct model...")
model_name = "ibm-granite/granite-3.1-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

print("Model loaded successfully!")

# Section topics
SECTIONS = {
    "1. Introduction": "Write a comprehensive introduction about audiobooks, explaining their significance in modern society.",
    "2. What are audiobooks?": "Define audiobooks in detail, explaining what they are and how they work.",
    "3. History of audiobooks": "Provide a detailed history of audiobooks from their inception to modern times.",
    "4. How audiobooks are made (step-by-step)": "Explain the step-by-step process of creating audiobooks, from recording to distribution.",
    "5. Types of audiobooks": "Describe different types of audiobooks including unabridged, abridged, full-cast, and more.",
    "6. Uses in education and daily life": "Explain how audiobooks are used in education and daily life activities.",
    "7. Advantages and disadvantages": "Discuss the pros and cons of audiobooks compared to traditional reading.",
    "8. Popular audiobook platforms": "List and describe popular audiobook platforms like Audible, Apple Books, etc.",
    "9. Future of audiobooks": "Discuss emerging trends and the future of audiobooks with AI and technology.",
    "10. Conclusion": "Write a compelling conclusion summarizing the importance of audiobooks.",
    "11. References": "Provide a list of academic and industry references for audiobook research."
}

def generate_section(section_title, prompt, max_tokens=800, temperature=0.7):
    """Generate content for a specific section using Granite model"""

    full_prompt = f"""You are an expert writer creating a comprehensive guide about audiobooks.

Task: {prompt}

Requirements:
- Write detailed, informative content
- Use professional academic tone
- Include specific examples and facts
- Make it engaging and well-structured
- Write 2-3 paragraphs minimum

Section: {section_title}

Content:"""

    inputs = tokenizer(full_prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=temperature,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract only the generated content
    if "Content:" in generated_text:
        content = generated_text.split("Content:")[-1].strip()
    else:
        content = generated_text[len(full_prompt):].strip()

    return content

def generate_complete_document(progress=gr.Progress()):
    """Generate the complete audiobook guide"""

    document = "# Complete Guide to Audiobooks\n\n"
    document += "Generated using IBM Granite 3.3 2B Instruct Model\n\n"
    document += "="*80 + "\n\n"

    total_sections = len(SECTIONS)

    for idx, (section_title, section_prompt) in enumerate(SECTIONS.items(), 1):
        progress((idx-1)/total_sections, desc=f"Generating {section_title}...")

        print(f"Generating {section_title}...")

        # Generate content for this section
        content = generate_section(section_title, section_prompt)

        # Add to document
        document += f"## {section_title}\n\n"
        document += f"{content}\n\n"
        document += "-"*80 + "\n\n"

    progress(1.0, desc="Complete!")
    return document

def generate_single_section(section_choice):
    """Generate a single section based on user selection"""

    if section_choice not in SECTIONS:
        return "Please select a valid section."

    print(f"Generating {section_choice}...")

    section_prompt = SECTIONS[section_choice]
    content = generate_section(section_choice, section_prompt)

    result = f"## {section_choice}\n\n{content}"
    return result

# Create Gradio Interface
with gr.Blocks(title="Audiobook Guide Generator", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 📚 Audiobook Guide Generator
    ### Powered by IBM Granite 3.3 2B Instruct Model

    Generate a comprehensive guide about audiobooks covering all major topics from introduction to future trends.
    """)

    with gr.Tab("📖 Generate Complete Document"):
        gr.Markdown("""
        Click the button below to generate a complete audiobook guide covering all 11 sections.
        This may take 5-10 minutes depending on your hardware.
        """)

        generate_btn = gr.Button("🚀 Generate Complete Guide", variant="primary", size="lg")
        output_complete = gr.Textbox(
            label="Generated Document",
            lines=30,
            max_lines=50,
            show_copy_button=True
        )

        generate_btn.click(
            fn=generate_complete_document,
            outputs=output_complete
        )

    with gr.Tab("📝 Generate Single Section"):
        gr.Markdown("""
        Generate individual sections of the audiobook guide.
        """)

        section_dropdown = gr.Dropdown(
            choices=list(SECTIONS.keys()),
            label="Select Section",
            value="1. Introduction"
        )

        generate_section_btn = gr.Button("Generate Section", variant="primary")
        output_section = gr.Textbox(
            label="Generated Section",
            lines=15,
            max_lines=30,
            show_copy_button=True
        )

        generate_section_btn.click(
            fn=generate_single_section,
            inputs=section_dropdown,
            outputs=output_section
        )

    with gr.Tab("ℹ️ About"):
        gr.Markdown("""
        ## About This Project

        This application generates comprehensive content about audiobooks using:

        - **Model**: IBM Granite 3.3 2B Instruct (from Hugging Face)
        - **Framework**: Transformers, PyTorch
        - **Interface**: Gradio
        - **Platform**: Google Colab

        ### Sections Covered:
        1. Introduction
        2. What are audiobooks?
        3. History of audiobooks
        4. How audiobooks are made (step-by-step)
        5. Types of audiobooks
        6. Uses in education and daily life
        7. Advantages and disadvantages
        8. Popular audiobook platforms
        9. Future of audiobooks
        10. Conclusion
        11. References

        ### Tips:
        - Generation time: ~30-60 seconds per section
        - Complete document: ~5-10 minutes
        - You can copy the output using the copy button
        - Results may vary slightly each time due to the generative nature of AI

        ---
        *Created for educational purposes*
        """)

# Launch the interface
print("\n" + "="*80)
print("Starting Gradio Interface...")
print("="*80 + "\n")

demo.launch(share=True, debug=True)

!pip install -q transformers accelerate gradio torch